version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: "deps(actions)"
    groups:
      github-actions-patch-minor:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      github-actions-major:
        patterns:
          - "*"
        update-types:
          - major

  - package-ecosystem: gomod
    directory: "/apps/backend"
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: "deps(go)"
    groups:
      go-patch-minor:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      go-major:
        patterns:
          - "*"
        update-types:
          - major

  - package-ecosystem: npm
    directory: "/apps/frontend"
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: "deps(npm)"
    groups:
      npm-patch-minor:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      npm-major:
        patterns:
          - "*"
        update-types:
          - major
