// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attachments.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO chat_attachments (
    session_id,
    message_id,
    blob_path,
    media_type,
    filename,
    size_bytes,
    sha256,
    provider_file_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING
    id,
    session_id,
    message_id,
    blob_path,
    media_type,
    filename,
    size_bytes,
    sha256,
    provider_file_id,
    created_at
`

type CreateAttachmentParams struct {
	SessionID      pgtype.UUID `json:"session_id"`
	MessageID      pgtype.UUID `json:"message_id"`
	BlobPath       string      `json:"blob_path"`
	MediaType      string      `json:"media_type"`
	Filename       string      `json:"filename"`
	SizeBytes      int64       `json:"size_bytes"`
	Sha256         string      `json:"sha256"`
	ProviderFileID pgtype.Text `json:"provider_file_id"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (ChatAttachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.SessionID,
		arg.MessageID,
		arg.BlobPath,
		arg.MediaType,
		arg.Filename,
		arg.SizeBytes,
		arg.Sha256,
		arg.ProviderFileID,
	)
	var i ChatAttachment
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.MessageID,
		&i.BlobPath,
		&i.MediaType,
		&i.Filename,
		&i.SizeBytes,
		&i.Sha256,
		&i.ProviderFileID,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachmentsByMessage = `-- name: ListAttachmentsByMessage :many
SELECT
    id,
    session_id,
    message_id,
    blob_path,
    media_type,
    filename,
    size_bytes,
    sha256,
    provider_file_id,
    created_at
FROM chat_attachments
WHERE message_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListAttachmentsByMessage(ctx context.Context, messageID pgtype.UUID) ([]ChatAttachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatAttachment
	for rows.Next() {
		var i ChatAttachment
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.MessageID,
			&i.BlobPath,
			&i.MediaType,
			&i.Filename,
			&i.SizeBytes,
			&i.Sha256,
			&i.ProviderFileID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
