// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: image_generation_assets.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createImageGenerationAsset = `-- name: CreateImageGenerationAsset :one
INSERT INTO image_generation_assets (
    generation_id,
    role,
    sort_order,
    blob_path,
    media_type,
    filename,
    size_bytes,
    sha256,
    width,
    height
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING
    id,
    generation_id,
    role,
    sort_order,
    blob_path,
    media_type,
    filename,
    size_bytes,
    sha256,
    width,
    height,
    created_at
`

type CreateImageGenerationAssetParams struct {
	GenerationID pgtype.UUID `json:"generation_id"`
	Role         string      `json:"role"`
	SortOrder    int64       `json:"sort_order"`
	BlobPath     string      `json:"blob_path"`
	MediaType    string      `json:"media_type"`
	Filename     string      `json:"filename"`
	SizeBytes    int64       `json:"size_bytes"`
	Sha256       string      `json:"sha256"`
	Width        pgtype.Int8 `json:"width"`
	Height       pgtype.Int8 `json:"height"`
}

func (q *Queries) CreateImageGenerationAsset(ctx context.Context, arg CreateImageGenerationAssetParams) (ImageGenerationAsset, error) {
	row := q.db.QueryRow(ctx, createImageGenerationAsset,
		arg.GenerationID,
		arg.Role,
		arg.SortOrder,
		arg.BlobPath,
		arg.MediaType,
		arg.Filename,
		arg.SizeBytes,
		arg.Sha256,
		arg.Width,
		arg.Height,
	)
	var i ImageGenerationAsset
	err := row.Scan(
		&i.ID,
		&i.GenerationID,
		&i.Role,
		&i.SortOrder,
		&i.BlobPath,
		&i.MediaType,
		&i.Filename,
		&i.SizeBytes,
		&i.Sha256,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
	)
	return i, err
}

const getImageGenerationAsset = `-- name: GetImageGenerationAsset :one
SELECT
    id,
    generation_id,
    role,
    sort_order,
    blob_path,
    media_type,
    filename,
    size_bytes,
    sha256,
    width,
    height,
    created_at
FROM image_generation_assets
WHERE id = $1
`

func (q *Queries) GetImageGenerationAsset(ctx context.Context, id pgtype.UUID) (ImageGenerationAsset, error) {
	row := q.db.QueryRow(ctx, getImageGenerationAsset, id)
	var i ImageGenerationAsset
	err := row.Scan(
		&i.ID,
		&i.GenerationID,
		&i.Role,
		&i.SortOrder,
		&i.BlobPath,
		&i.MediaType,
		&i.Filename,
		&i.SizeBytes,
		&i.Sha256,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
	)
	return i, err
}

const getImageGenerationAssetBySession = `-- name: GetImageGenerationAssetBySession :one
SELECT
    a.id,
    a.generation_id,
    a.role,
    a.sort_order,
    a.blob_path,
    a.media_type,
    a.filename,
    a.size_bytes,
    a.sha256,
    a.width,
    a.height,
    a.created_at
FROM image_generation_assets AS a
JOIN image_generations AS g
    ON g.id = a.generation_id
WHERE a.id = $1
  AND g.session_id = $2
`

type GetImageGenerationAssetBySessionParams struct {
	ID        pgtype.UUID `json:"id"`
	SessionID pgtype.UUID `json:"session_id"`
}

func (q *Queries) GetImageGenerationAssetBySession(ctx context.Context, arg GetImageGenerationAssetBySessionParams) (ImageGenerationAsset, error) {
	row := q.db.QueryRow(ctx, getImageGenerationAssetBySession, arg.ID, arg.SessionID)
	var i ImageGenerationAsset
	err := row.Scan(
		&i.ID,
		&i.GenerationID,
		&i.Role,
		&i.SortOrder,
		&i.BlobPath,
		&i.MediaType,
		&i.Filename,
		&i.SizeBytes,
		&i.Sha256,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
	)
	return i, err
}

const listImageGenerationAssetsByGeneration = `-- name: ListImageGenerationAssetsByGeneration :many
SELECT
    id,
    generation_id,
    role,
    sort_order,
    blob_path,
    media_type,
    filename,
    size_bytes,
    sha256,
    width,
    height,
    created_at
FROM image_generation_assets
WHERE generation_id = $1
ORDER BY role ASC, sort_order ASC, created_at ASC, id ASC
`

func (q *Queries) ListImageGenerationAssetsByGeneration(ctx context.Context, generationID pgtype.UUID) ([]ImageGenerationAsset, error) {
	rows, err := q.db.Query(ctx, listImageGenerationAssetsByGeneration, generationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImageGenerationAsset
	for rows.Next() {
		var i ImageGenerationAsset
		if err := rows.Scan(
			&i.ID,
			&i.GenerationID,
			&i.Role,
			&i.SortOrder,
			&i.BlobPath,
			&i.MediaType,
			&i.Filename,
			&i.SizeBytes,
			&i.Sha256,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImageGenerationAssetsByGenerationAndSession = `-- name: ListImageGenerationAssetsByGenerationAndSession :many
SELECT
    a.id,
    a.generation_id,
    a.role,
    a.sort_order,
    a.blob_path,
    a.media_type,
    a.filename,
    a.size_bytes,
    a.sha256,
    a.width,
    a.height,
    a.created_at
FROM image_generation_assets AS a
JOIN image_generations AS g
    ON g.id = a.generation_id
WHERE a.generation_id = $1
  AND g.session_id = $2
ORDER BY a.role ASC, a.sort_order ASC, a.created_at ASC, a.id ASC
`

type ListImageGenerationAssetsByGenerationAndSessionParams struct {
	GenerationID pgtype.UUID `json:"generation_id"`
	SessionID    pgtype.UUID `json:"session_id"`
}

func (q *Queries) ListImageGenerationAssetsByGenerationAndSession(ctx context.Context, arg ListImageGenerationAssetsByGenerationAndSessionParams) ([]ImageGenerationAsset, error) {
	rows, err := q.db.Query(ctx, listImageGenerationAssetsByGenerationAndSession, arg.GenerationID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImageGenerationAsset
	for rows.Next() {
		var i ImageGenerationAsset
		if err := rows.Scan(
			&i.ID,
			&i.GenerationID,
			&i.Role,
			&i.SortOrder,
			&i.BlobPath,
			&i.MediaType,
			&i.Filename,
			&i.SizeBytes,
			&i.Sha256,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
