// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: image_generations.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createImageGeneration = `-- name: CreateImageGeneration :one
INSERT INTO image_generations (
    session_id,
    mode,
    prompt,
    resolution_key,
    width,
    height,
    requested_image_count,
    provider_name,
    provider_model,
    provider_job_id,
    status,
    error_code,
    error_message,
    completed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14
)
RETURNING
    id,
    session_id,
    mode,
    prompt,
    resolution_key,
    width,
    height,
    requested_image_count,
    provider_name,
    provider_model,
    provider_job_id,
    status,
    error_code,
    error_message,
    created_at,
    completed_at
`

type CreateImageGenerationParams struct {
	SessionID           pgtype.UUID        `json:"session_id"`
	Mode                string             `json:"mode"`
	Prompt              string             `json:"prompt"`
	ResolutionKey       string             `json:"resolution_key"`
	Width               int64              `json:"width"`
	Height              int64              `json:"height"`
	RequestedImageCount int64              `json:"requested_image_count"`
	ProviderName        string             `json:"provider_name"`
	ProviderModel       string             `json:"provider_model"`
	ProviderJobID       pgtype.Text        `json:"provider_job_id"`
	Status              string             `json:"status"`
	ErrorCode           pgtype.Text        `json:"error_code"`
	ErrorMessage        pgtype.Text        `json:"error_message"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) CreateImageGeneration(ctx context.Context, arg CreateImageGenerationParams) (ImageGeneration, error) {
	row := q.db.QueryRow(ctx, createImageGeneration,
		arg.SessionID,
		arg.Mode,
		arg.Prompt,
		arg.ResolutionKey,
		arg.Width,
		arg.Height,
		arg.RequestedImageCount,
		arg.ProviderName,
		arg.ProviderModel,
		arg.ProviderJobID,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.CompletedAt,
	)
	var i ImageGeneration
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Mode,
		&i.Prompt,
		&i.ResolutionKey,
		&i.Width,
		&i.Height,
		&i.RequestedImageCount,
		&i.ProviderName,
		&i.ProviderModel,
		&i.ProviderJobID,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const claimPendingImageGeneration = `-- name: ClaimPendingImageGeneration :execrows
UPDATE image_generations
SET provider_name = $2,
    provider_model = $3,
    provider_job_id = NULL,
    status = 'running',
    error_code = NULL,
    error_message = NULL,
    completed_at = NULL
WHERE id = $1
  AND status = 'pending'
`

type ClaimPendingImageGenerationParams struct {
	ID            pgtype.UUID `json:"id"`
	ProviderName  string      `json:"provider_name"`
	ProviderModel string      `json:"provider_model"`
}

func (q *Queries) ClaimPendingImageGeneration(ctx context.Context, arg ClaimPendingImageGenerationParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimPendingImageGeneration, arg.ID, arg.ProviderName, arg.ProviderModel)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getImageGeneration = `-- name: GetImageGeneration :one
SELECT
    id,
    session_id,
    mode,
    prompt,
    resolution_key,
    width,
    height,
    requested_image_count,
    provider_name,
    provider_model,
    provider_job_id,
    status,
    error_code,
    error_message,
    created_at,
    completed_at
FROM image_generations
WHERE id = $1
`

func (q *Queries) GetImageGeneration(ctx context.Context, id pgtype.UUID) (ImageGeneration, error) {
	row := q.db.QueryRow(ctx, getImageGeneration, id)
	var i ImageGeneration
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Mode,
		&i.Prompt,
		&i.ResolutionKey,
		&i.Width,
		&i.Height,
		&i.RequestedImageCount,
		&i.ProviderName,
		&i.ProviderModel,
		&i.ProviderJobID,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getImageGenerationBySession = `-- name: GetImageGenerationBySession :one
SELECT
    id,
    session_id,
    mode,
    prompt,
    resolution_key,
    width,
    height,
    requested_image_count,
    provider_name,
    provider_model,
    provider_job_id,
    status,
    error_code,
    error_message,
    created_at,
    completed_at
FROM image_generations
WHERE id = $1
  AND session_id = $2
`

type GetImageGenerationBySessionParams struct {
	ID        pgtype.UUID `json:"id"`
	SessionID pgtype.UUID `json:"session_id"`
}

func (q *Queries) GetImageGenerationBySession(ctx context.Context, arg GetImageGenerationBySessionParams) (ImageGeneration, error) {
	row := q.db.QueryRow(ctx, getImageGenerationBySession, arg.ID, arg.SessionID)
	var i ImageGeneration
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Mode,
		&i.Prompt,
		&i.ResolutionKey,
		&i.Width,
		&i.Height,
		&i.RequestedImageCount,
		&i.ProviderName,
		&i.ProviderModel,
		&i.ProviderJobID,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listImageGenerationsBySession = `-- name: ListImageGenerationsBySession :many
SELECT
    id,
    session_id,
    mode,
    prompt,
    resolution_key,
    width,
    height,
    requested_image_count,
    provider_name,
    provider_model,
    provider_job_id,
    status,
    error_code,
    error_message,
    created_at,
    completed_at
FROM image_generations
WHERE session_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListImageGenerationsBySession(ctx context.Context, sessionID pgtype.UUID) ([]ImageGeneration, error) {
	rows, err := q.db.Query(ctx, listImageGenerationsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImageGeneration
	for rows.Next() {
		var i ImageGeneration
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Mode,
			&i.Prompt,
			&i.ResolutionKey,
			&i.Width,
			&i.Height,
			&i.RequestedImageCount,
			&i.ProviderName,
			&i.ProviderModel,
			&i.ProviderJobID,
			&i.Status,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockImageGenerationForUpdate = `-- name: LockImageGenerationForUpdate :one
SELECT
    id,
    session_id,
    mode,
    prompt,
    resolution_key,
    width,
    height,
    requested_image_count,
    provider_name,
    provider_model,
    provider_job_id,
    status,
    error_code,
    error_message,
    created_at,
    completed_at
FROM image_generations
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockImageGenerationForUpdate(ctx context.Context, id pgtype.UUID) (ImageGeneration, error) {
	row := q.db.QueryRow(ctx, lockImageGenerationForUpdate, id)
	var i ImageGeneration
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Mode,
		&i.Prompt,
		&i.ResolutionKey,
		&i.Width,
		&i.Height,
		&i.RequestedImageCount,
		&i.ProviderName,
		&i.ProviderModel,
		&i.ProviderJobID,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateImageGenerationState = `-- name: UpdateImageGenerationState :execrows
UPDATE image_generations
SET provider_name = $2,
    provider_model = $3,
    provider_job_id = $4,
    status = $5,
    error_code = $6,
    error_message = $7,
    completed_at = $8
WHERE id = $1
`

type UpdateImageGenerationStateParams struct {
	ID            pgtype.UUID        `json:"id"`
	ProviderName  string             `json:"provider_name"`
	ProviderModel string             `json:"provider_model"`
	ProviderJobID pgtype.Text        `json:"provider_job_id"`
	Status        string             `json:"status"`
	ErrorCode     pgtype.Text        `json:"error_code"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateImageGenerationState(ctx context.Context, arg UpdateImageGenerationStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateImageGenerationState,
		arg.ID,
		arg.ProviderName,
		arg.ProviderModel,
		arg.ProviderJobID,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.CompletedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
