// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO chat_messages (
    session_id,
    role,
    content_json,
    status,
    model_name
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, session_id, role, content_json, status, model_name, created_at
`

type CreateMessageParams struct {
	SessionID   pgtype.UUID `json:"session_id"`
	Role        string      `json:"role"`
	ContentJson []byte      `json:"content_json"`
	Status      string      `json:"status"`
	ModelName   pgtype.Text `json:"model_name"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.SessionID,
		arg.Role,
		arg.ContentJson,
		arg.Status,
		arg.ModelName,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.ContentJson,
		&i.Status,
		&i.ModelName,
		&i.CreatedAt,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, session_id, role, content_json, status, model_name, created_at
FROM chat_messages
WHERE id = $1
`

func (q *Queries) GetMessage(ctx context.Context, id pgtype.UUID) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.ContentJson,
		&i.Status,
		&i.ModelName,
		&i.CreatedAt,
	)
	return i, err
}

const listMessagesBySession = `-- name: ListMessagesBySession :many
SELECT id, session_id, role, content_json, status, model_name, created_at
FROM chat_messages
WHERE session_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListMessagesBySession(ctx context.Context, sessionID pgtype.UUID) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, listMessagesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.ContentJson,
			&i.Status,
			&i.ModelName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessageContentStatusAndModel = `-- name: UpdateMessageContentStatusAndModel :execrows
UPDATE chat_messages
SET content_json = $2,
    status = $3,
    model_name = $4
WHERE id = $1
`

type UpdateMessageContentStatusAndModelParams struct {
	ID          pgtype.UUID `json:"id"`
	ContentJson []byte      `json:"content_json"`
	Status      string      `json:"status"`
	ModelName   pgtype.Text `json:"model_name"`
}

func (q *Queries) UpdateMessageContentStatusAndModel(ctx context.Context, arg UpdateMessageContentStatusAndModelParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMessageContentStatusAndModel,
		arg.ID,
		arg.ContentJson,
		arg.Status,
		arg.ModelName,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMessageStatusAndModel = `-- name: UpdateMessageStatusAndModel :exec
UPDATE chat_messages
SET status = $2,
    model_name = $3
WHERE id = $1
`

type UpdateMessageStatusAndModelParams struct {
	ID        pgtype.UUID `json:"id"`
	Status    string      `json:"status"`
	ModelName pgtype.Text `json:"model_name"`
}

func (q *Queries) UpdateMessageStatusAndModel(ctx context.Context, arg UpdateMessageStatusAndModelParams) error {
	_, err := q.db.Exec(ctx, updateMessageStatusAndModel, arg.ID, arg.Status, arg.ModelName)
	return err
}
