// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ChatAttachment struct {
	ID             pgtype.UUID        `json:"id"`
	SessionID      pgtype.UUID        `json:"session_id"`
	MessageID      pgtype.UUID        `json:"message_id"`
	BlobPath       string             `json:"blob_path"`
	MediaType      string             `json:"media_type"`
	Filename       string             `json:"filename"`
	SizeBytes      int64              `json:"size_bytes"`
	Sha256         string             `json:"sha256"`
	ProviderFileID pgtype.Text        `json:"provider_file_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ChatMessage struct {
	ID          pgtype.UUID        `json:"id"`
	SessionID   pgtype.UUID        `json:"session_id"`
	Role        string             `json:"role"`
	ContentJson []byte             `json:"content_json"`
	Status      string             `json:"status"`
	ModelName   pgtype.Text        `json:"model_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ChatRun struct {
	ID                 pgtype.UUID        `json:"id"`
	SessionID          pgtype.UUID        `json:"session_id"`
	UserMessageID      pgtype.UUID        `json:"user_message_id"`
	AssistantMessageID pgtype.UUID        `json:"assistant_message_id"`
	ProviderResponseID pgtype.Text        `json:"provider_response_id"`
	InputTokens        pgtype.Int8        `json:"input_tokens"`
	OutputTokens       pgtype.Int8        `json:"output_tokens"`
	TotalTokens        pgtype.Int8        `json:"total_tokens"`
	Status             string             `json:"status"`
	ErrorCode          pgtype.Text        `json:"error_code"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
}

type ChatSession struct {
	ID            pgtype.UUID        `json:"id"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
}

type ImageGeneration struct {
	ID                  pgtype.UUID        `json:"id"`
	SessionID           pgtype.UUID        `json:"session_id"`
	Mode                string             `json:"mode"`
	Prompt              string             `json:"prompt"`
	ResolutionKey       string             `json:"resolution_key"`
	Width               int64              `json:"width"`
	Height              int64              `json:"height"`
	RequestedImageCount int64              `json:"requested_image_count"`
	ProviderName        string             `json:"provider_name"`
	ProviderModel       string             `json:"provider_model"`
	ProviderJobID       pgtype.Text        `json:"provider_job_id"`
	Status              string             `json:"status"`
	ErrorCode           pgtype.Text        `json:"error_code"`
	ErrorMessage        pgtype.Text        `json:"error_message"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
}

type ImageGenerationAsset struct {
	ID           pgtype.UUID        `json:"id"`
	GenerationID pgtype.UUID        `json:"generation_id"`
	Role         string             `json:"role"`
	SortOrder    int64              `json:"sort_order"`
	BlobPath     string             `json:"blob_path"`
	MediaType    string             `json:"media_type"`
	Filename     string             `json:"filename"`
	SizeBytes    int64              `json:"size_bytes"`
	Sha256       string             `json:"sha256"`
	Width        pgtype.Int8        `json:"width"`
	Height       pgtype.Int8        `json:"height"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
