// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: presentation_generations.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingPresentationGeneration = `-- name: ClaimPendingPresentationGeneration :execrows
UPDATE presentation_generations
SET provider_name = $2,
    provider_model = $3,
    provider_job_id = NULL,
    status = 'running',
    error_code = NULL,
    error_message = NULL,
    started_at = NOW(),
    completed_at = NULL
WHERE id = $1
  AND status = 'pending'
`

type ClaimPendingPresentationGenerationParams struct {
	ID            pgtype.UUID `json:"id"`
	ProviderName  string      `json:"provider_name"`
	ProviderModel string      `json:"provider_model"`
}

func (q *Queries) ClaimPendingPresentationGeneration(ctx context.Context, arg ClaimPendingPresentationGenerationParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimPendingPresentationGeneration, arg.ID, arg.ProviderName, arg.ProviderModel)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createPresentationGeneration = `-- name: CreatePresentationGeneration :one
INSERT INTO presentation_generations (
    session_id,
    prompt,
    dialect_json,
    provider_name,
    provider_model,
    provider_job_id,
    status,
    error_code,
    error_message,
    completed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING
    id,
    session_id,
    prompt,
    dialect_json,
    provider_name,
    provider_model,
    provider_job_id,
    status,
    error_code,
    error_message,
    created_at,
    started_at,
    completed_at
`

type CreatePresentationGenerationParams struct {
	SessionID     pgtype.UUID        `json:"session_id"`
	Prompt        string             `json:"prompt"`
	DialectJson   []byte             `json:"dialect_json"`
	ProviderName  string             `json:"provider_name"`
	ProviderModel string             `json:"provider_model"`
	ProviderJobID pgtype.Text        `json:"provider_job_id"`
	Status        string             `json:"status"`
	ErrorCode     pgtype.Text        `json:"error_code"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) CreatePresentationGeneration(ctx context.Context, arg CreatePresentationGenerationParams) (PresentationGeneration, error) {
	row := q.db.QueryRow(ctx, createPresentationGeneration,
		arg.SessionID,
		arg.Prompt,
		arg.DialectJson,
		arg.ProviderName,
		arg.ProviderModel,
		arg.ProviderJobID,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.CompletedAt,
	)
	var i PresentationGeneration
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Prompt,
		&i.DialectJson,
		&i.ProviderName,
		&i.ProviderModel,
		&i.ProviderJobID,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getPresentationGeneration = `-- name: GetPresentationGeneration :one
SELECT
    id,
    session_id,
    prompt,
    dialect_json,
    provider_name,
    provider_model,
    provider_job_id,
    status,
    error_code,
    error_message,
    created_at,
    started_at,
    completed_at
FROM presentation_generations
WHERE id = $1
`

func (q *Queries) GetPresentationGeneration(ctx context.Context, id pgtype.UUID) (PresentationGeneration, error) {
	row := q.db.QueryRow(ctx, getPresentationGeneration, id)
	var i PresentationGeneration
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Prompt,
		&i.DialectJson,
		&i.ProviderName,
		&i.ProviderModel,
		&i.ProviderJobID,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getPresentationGenerationBySession = `-- name: GetPresentationGenerationBySession :one
SELECT
    id,
    session_id,
    prompt,
    dialect_json,
    provider_name,
    provider_model,
    provider_job_id,
    status,
    error_code,
    error_message,
    created_at,
    started_at,
    completed_at
FROM presentation_generations
WHERE id = $1
  AND session_id = $2
`

type GetPresentationGenerationBySessionParams struct {
	ID        pgtype.UUID `json:"id"`
	SessionID pgtype.UUID `json:"session_id"`
}

func (q *Queries) GetPresentationGenerationBySession(ctx context.Context, arg GetPresentationGenerationBySessionParams) (PresentationGeneration, error) {
	row := q.db.QueryRow(ctx, getPresentationGenerationBySession, arg.ID, arg.SessionID)
	var i PresentationGeneration
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Prompt,
		&i.DialectJson,
		&i.ProviderName,
		&i.ProviderModel,
		&i.ProviderJobID,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listPresentationGenerationsBySession = `-- name: ListPresentationGenerationsBySession :many
SELECT
    id,
    session_id,
    prompt,
    dialect_json,
    provider_name,
    provider_model,
    provider_job_id,
    status,
    error_code,
    error_message,
    created_at,
    started_at,
    completed_at
FROM presentation_generations
WHERE session_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListPresentationGenerationsBySession(ctx context.Context, sessionID pgtype.UUID) ([]PresentationGeneration, error) {
	rows, err := q.db.Query(ctx, listPresentationGenerationsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PresentationGeneration
	for rows.Next() {
		var i PresentationGeneration
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Prompt,
			&i.DialectJson,
			&i.ProviderName,
			&i.ProviderModel,
			&i.ProviderJobID,
			&i.Status,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPresentationGenerationForUpdate = `-- name: LockPresentationGenerationForUpdate :one
SELECT
    id,
    session_id,
    prompt,
    dialect_json,
    provider_name,
    provider_model,
    provider_job_id,
    status,
    error_code,
    error_message,
    created_at,
    started_at,
    completed_at
FROM presentation_generations
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockPresentationGenerationForUpdate(ctx context.Context, id pgtype.UUID) (PresentationGeneration, error) {
	row := q.db.QueryRow(ctx, lockPresentationGenerationForUpdate, id)
	var i PresentationGeneration
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Prompt,
		&i.DialectJson,
		&i.ProviderName,
		&i.ProviderModel,
		&i.ProviderJobID,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updatePresentationGenerationState = `-- name: UpdatePresentationGenerationState :execrows
UPDATE presentation_generations
SET provider_name = $2,
    provider_model = $3,
    provider_job_id = $4,
    status = $5,
    error_code = $6,
    error_message = $7,
    completed_at = $8,
    dialect_json = $9
WHERE id = $1
`

type UpdatePresentationGenerationStateParams struct {
	ID            pgtype.UUID        `json:"id"`
	ProviderName  string             `json:"provider_name"`
	ProviderModel string             `json:"provider_model"`
	ProviderJobID pgtype.Text        `json:"provider_job_id"`
	Status        string             `json:"status"`
	ErrorCode     pgtype.Text        `json:"error_code"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	DialectJson   []byte             `json:"dialect_json"`
}

func (q *Queries) UpdatePresentationGenerationState(ctx context.Context, arg UpdatePresentationGenerationStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePresentationGenerationState,
		arg.ID,
		arg.ProviderName,
		arg.ProviderModel,
		arg.ProviderJobID,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.CompletedAt,
		arg.DialectJson,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
