// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: presentation_generation_assets.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPresentationGenerationAsset = `-- name: CreatePresentationGenerationAsset :one
INSERT INTO presentation_generation_assets (
    generation_id,
    role,
    sort_order,
    blob_path,
    media_type,
    filename,
    size_bytes,
    sha256
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING
    id,
    generation_id,
    role,
    sort_order,
    blob_path,
    media_type,
    filename,
    size_bytes,
    sha256,
    created_at
`

type CreatePresentationGenerationAssetParams struct {
	GenerationID pgtype.UUID `json:"generation_id"`
	Role         string      `json:"role"`
	SortOrder    int64       `json:"sort_order"`
	BlobPath     string      `json:"blob_path"`
	MediaType    string      `json:"media_type"`
	Filename     string      `json:"filename"`
	SizeBytes    int64       `json:"size_bytes"`
	Sha256       string      `json:"sha256"`
}

func (q *Queries) CreatePresentationGenerationAsset(ctx context.Context, arg CreatePresentationGenerationAssetParams) (PresentationGenerationAsset, error) {
	row := q.db.QueryRow(ctx, createPresentationGenerationAsset,
		arg.GenerationID,
		arg.Role,
		arg.SortOrder,
		arg.BlobPath,
		arg.MediaType,
		arg.Filename,
		arg.SizeBytes,
		arg.Sha256,
	)
	var i PresentationGenerationAsset
	err := row.Scan(
		&i.ID,
		&i.GenerationID,
		&i.Role,
		&i.SortOrder,
		&i.BlobPath,
		&i.MediaType,
		&i.Filename,
		&i.SizeBytes,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const getPresentationGenerationAsset = `-- name: GetPresentationGenerationAsset :one
SELECT
    id,
    generation_id,
    role,
    sort_order,
    blob_path,
    media_type,
    filename,
    size_bytes,
    sha256,
    created_at
FROM presentation_generation_assets
WHERE id = $1
`

func (q *Queries) GetPresentationGenerationAsset(ctx context.Context, id pgtype.UUID) (PresentationGenerationAsset, error) {
	row := q.db.QueryRow(ctx, getPresentationGenerationAsset, id)
	var i PresentationGenerationAsset
	err := row.Scan(
		&i.ID,
		&i.GenerationID,
		&i.Role,
		&i.SortOrder,
		&i.BlobPath,
		&i.MediaType,
		&i.Filename,
		&i.SizeBytes,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const getPresentationGenerationAssetBySession = `-- name: GetPresentationGenerationAssetBySession :one
SELECT
    a.id,
    a.generation_id,
    a.role,
    a.sort_order,
    a.blob_path,
    a.media_type,
    a.filename,
    a.size_bytes,
    a.sha256,
    a.created_at
FROM presentation_generation_assets AS a
JOIN presentation_generations AS g
    ON g.id = a.generation_id
WHERE a.id = $1
  AND g.session_id = $2
`

type GetPresentationGenerationAssetBySessionParams struct {
	ID        pgtype.UUID `json:"id"`
	SessionID pgtype.UUID `json:"session_id"`
}

func (q *Queries) GetPresentationGenerationAssetBySession(ctx context.Context, arg GetPresentationGenerationAssetBySessionParams) (PresentationGenerationAsset, error) {
	row := q.db.QueryRow(ctx, getPresentationGenerationAssetBySession, arg.ID, arg.SessionID)
	var i PresentationGenerationAsset
	err := row.Scan(
		&i.ID,
		&i.GenerationID,
		&i.Role,
		&i.SortOrder,
		&i.BlobPath,
		&i.MediaType,
		&i.Filename,
		&i.SizeBytes,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const listPresentationGenerationAssetsByGeneration = `-- name: ListPresentationGenerationAssetsByGeneration :many
SELECT
    id,
    generation_id,
    role,
    sort_order,
    blob_path,
    media_type,
    filename,
    size_bytes,
    sha256,
    created_at
FROM presentation_generation_assets
WHERE generation_id = $1
ORDER BY role ASC, sort_order ASC, created_at ASC, id ASC
`

func (q *Queries) ListPresentationGenerationAssetsByGeneration(ctx context.Context, generationID pgtype.UUID) ([]PresentationGenerationAsset, error) {
	rows, err := q.db.Query(ctx, listPresentationGenerationAssetsByGeneration, generationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PresentationGenerationAsset
	for rows.Next() {
		var i PresentationGenerationAsset
		if err := rows.Scan(
			&i.ID,
			&i.GenerationID,
			&i.Role,
			&i.SortOrder,
			&i.BlobPath,
			&i.MediaType,
			&i.Filename,
			&i.SizeBytes,
			&i.Sha256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPresentationGenerationAssetsByGenerationAndSession = `-- name: ListPresentationGenerationAssetsByGenerationAndSession :many
SELECT
    a.id,
    a.generation_id,
    a.role,
    a.sort_order,
    a.blob_path,
    a.media_type,
    a.filename,
    a.size_bytes,
    a.sha256,
    a.created_at
FROM presentation_generation_assets AS a
JOIN presentation_generations AS g
    ON g.id = a.generation_id
WHERE a.generation_id = $1
  AND g.session_id = $2
ORDER BY a.role ASC, a.sort_order ASC, a.created_at ASC, a.id ASC
`

type ListPresentationGenerationAssetsByGenerationAndSessionParams struct {
	GenerationID pgtype.UUID `json:"generation_id"`
	SessionID    pgtype.UUID `json:"session_id"`
}

func (q *Queries) ListPresentationGenerationAssetsByGenerationAndSession(ctx context.Context, arg ListPresentationGenerationAssetsByGenerationAndSessionParams) ([]PresentationGenerationAsset, error) {
	rows, err := q.db.Query(ctx, listPresentationGenerationAssetsByGenerationAndSession, arg.GenerationID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PresentationGenerationAsset
	for rows.Next() {
		var i PresentationGenerationAsset
		if err := rows.Scan(
			&i.ID,
			&i.GenerationID,
			&i.Role,
			&i.SortOrder,
			&i.BlobPath,
			&i.MediaType,
			&i.Filename,
			&i.SizeBytes,
			&i.Sha256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
