// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRun = `-- name: CreateRun :one
INSERT INTO chat_runs (
    session_id,
    user_message_id,
    assistant_message_id,
    provider_response_id,
    input_tokens,
    output_tokens,
    total_tokens,
    status,
    error_code,
    started_at,
    completed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING
    id,
    session_id,
    user_message_id,
    assistant_message_id,
    provider_response_id,
    input_tokens,
    output_tokens,
    total_tokens,
    status,
    error_code,
    started_at,
    completed_at
`

type CreateRunParams struct {
	SessionID          pgtype.UUID        `json:"session_id"`
	UserMessageID      pgtype.UUID        `json:"user_message_id"`
	AssistantMessageID pgtype.UUID        `json:"assistant_message_id"`
	ProviderResponseID pgtype.Text        `json:"provider_response_id"`
	InputTokens        pgtype.Int8        `json:"input_tokens"`
	OutputTokens       pgtype.Int8        `json:"output_tokens"`
	TotalTokens        pgtype.Int8        `json:"total_tokens"`
	Status             string             `json:"status"`
	ErrorCode          pgtype.Text        `json:"error_code"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (ChatRun, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.SessionID,
		arg.UserMessageID,
		arg.AssistantMessageID,
		arg.ProviderResponseID,
		arg.InputTokens,
		arg.OutputTokens,
		arg.TotalTokens,
		arg.Status,
		arg.ErrorCode,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i ChatRun
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.ProviderResponseID,
		&i.InputTokens,
		&i.OutputTokens,
		&i.TotalTokens,
		&i.Status,
		&i.ErrorCode,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT
    id,
    session_id,
    user_message_id,
    assistant_message_id,
    provider_response_id,
    input_tokens,
    output_tokens,
    total_tokens,
    status,
    error_code,
    started_at,
    completed_at
FROM chat_runs
WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id pgtype.UUID) (ChatRun, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i ChatRun
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.ProviderResponseID,
		&i.InputTokens,
		&i.OutputTokens,
		&i.TotalTokens,
		&i.Status,
		&i.ErrorCode,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listRunsBySession = `-- name: ListRunsBySession :many
SELECT
    id,
    session_id,
    user_message_id,
    assistant_message_id,
    provider_response_id,
    input_tokens,
    output_tokens,
    total_tokens,
    status,
    error_code,
    started_at,
    completed_at
FROM chat_runs
WHERE session_id = $1
ORDER BY started_at, id
`

func (q *Queries) ListRunsBySession(ctx context.Context, sessionID pgtype.UUID) ([]ChatRun, error) {
	rows, err := q.db.Query(ctx, listRunsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatRun
	for rows.Next() {
		var i ChatRun
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.UserMessageID,
			&i.AssistantMessageID,
			&i.ProviderResponseID,
			&i.InputTokens,
			&i.OutputTokens,
			&i.TotalTokens,
			&i.Status,
			&i.ErrorCode,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunState = `-- name: UpdateRunState :execrows
UPDATE chat_runs
SET assistant_message_id = $2,
    provider_response_id = $3,
    input_tokens = $4,
    output_tokens = $5,
    total_tokens = $6,
    status = $7,
    error_code = $8,
    completed_at = $9
WHERE id = $1
`

type UpdateRunStateParams struct {
	ID                 pgtype.UUID        `json:"id"`
	AssistantMessageID pgtype.UUID        `json:"assistant_message_id"`
	ProviderResponseID pgtype.Text        `json:"provider_response_id"`
	InputTokens        pgtype.Int8        `json:"input_tokens"`
	OutputTokens       pgtype.Int8        `json:"output_tokens"`
	TotalTokens        pgtype.Int8        `json:"total_tokens"`
	Status             string             `json:"status"`
	ErrorCode          pgtype.Text        `json:"error_code"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateRunState(ctx context.Context, arg UpdateRunStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRunState,
		arg.ID,
		arg.AssistantMessageID,
		arg.ProviderResponseID,
		arg.InputTokens,
		arg.OutputTokens,
		arg.TotalTokens,
		arg.Status,
		arg.ErrorCode,
		arg.CompletedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
