// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRun = `-- name: CreateRun :one
INSERT INTO chat_runs (
    session_id,
    user_message_id,
    assistant_message_id,
    provider_response_id,
    status,
    error_code,
    started_at,
    completed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING
    id,
    session_id,
    user_message_id,
    assistant_message_id,
    provider_response_id,
    status,
    error_code,
    started_at,
    completed_at
`

type CreateRunParams struct {
	SessionID          pgtype.UUID        `json:"session_id"`
	UserMessageID      pgtype.UUID        `json:"user_message_id"`
	AssistantMessageID pgtype.UUID        `json:"assistant_message_id"`
	ProviderResponseID pgtype.Text        `json:"provider_response_id"`
	Status             string             `json:"status"`
	ErrorCode          pgtype.Text        `json:"error_code"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (ChatRun, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.SessionID,
		arg.UserMessageID,
		arg.AssistantMessageID,
		arg.ProviderResponseID,
		arg.Status,
		arg.ErrorCode,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i ChatRun
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.ProviderResponseID,
		&i.Status,
		&i.ErrorCode,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT
    id,
    session_id,
    user_message_id,
    assistant_message_id,
    provider_response_id,
    status,
    error_code,
    started_at,
    completed_at
FROM chat_runs
WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id pgtype.UUID) (ChatRun, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i ChatRun
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.ProviderResponseID,
		&i.Status,
		&i.ErrorCode,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateRunState = `-- name: UpdateRunState :execrows
UPDATE chat_runs
SET assistant_message_id = $2,
    provider_response_id = $3,
    status = $4,
    error_code = $5,
    completed_at = $6
WHERE id = $1
`

type UpdateRunStateParams struct {
	ID                 pgtype.UUID        `json:"id"`
	AssistantMessageID pgtype.UUID        `json:"assistant_message_id"`
	ProviderResponseID pgtype.Text        `json:"provider_response_id"`
	Status             string             `json:"status"`
	ErrorCode          pgtype.Text        `json:"error_code"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateRunState(ctx context.Context, arg UpdateRunStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRunState,
		arg.ID,
		arg.AssistantMessageID,
		arg.ProviderResponseID,
		arg.Status,
		arg.ErrorCode,
		arg.CompletedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
