// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO chat_sessions DEFAULT VALUES
RETURNING id, status, title, created_at, last_message_at
`

func (q *Queries) CreateSession(ctx context.Context) (ChatSession, error) {
	row := q.db.QueryRow(ctx, createSession)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Title,
		&i.CreatedAt,
		&i.LastMessageAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, status, title, created_at, last_message_at
FROM chat_sessions
WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id pgtype.UUID) (ChatSession, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Title,
		&i.CreatedAt,
		&i.LastMessageAt,
	)
	return i, err
}

const touchSessionLastMessageAt = `-- name: TouchSessionLastMessageAt :execrows
UPDATE chat_sessions
SET last_message_at = NOW()
WHERE id = $1
`

func (q *Queries) TouchSessionLastMessageAt(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, touchSessionLastMessageAt, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSessionTitleIfEmpty = `-- name: SetSessionTitleIfEmpty :execrows
UPDATE chat_sessions
SET title = $2
WHERE id = $1
  AND (title IS NULL OR title = '')
`

type SetSessionTitleIfEmptyParams struct {
	ID    pgtype.UUID `json:"id"`
	Title pgtype.Text `json:"title"`
}

func (q *Queries) SetSessionTitleIfEmpty(ctx context.Context, arg SetSessionTitleIfEmptyParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSessionTitleIfEmpty, arg.ID, arg.Title)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
