export const markdownAssistantReply = [
  "# Plan",
  "",
  "Intro with **bold**, *italic*, ~~strikethrough~~, and a [Docs](https://example.com) link.",
  "",
  "1. First item",
  "2. Second item",
  "",
  "- Bullet one",
  "- Bullet two",
  "",
  "> Helpful note",
  "",
  "- [x] Done",
  "- [ ] Pending",
  "",
  "| Name | Value |",
  "| --- | --- |",
  "| Alpha | 1 |",
  "",
  "```ts",
  "const answer = 42;",
  "```",
].join("\n");
